-- Analyst EOD summaries table - aggregates daily analysis
-- 30-minute summaries are stored on disk in data/summaries/
-- Only end-of-day comprehensive summaries are persisted to database

CREATE TABLE IF NOT EXISTS analyst_summaries (
    symbol VARCHAR NOT NULL,
    date_only DATE NOT NULL,  -- Trading date for this EOD summary
    timestamp TIMESTAMP NOT NULL,  -- EOD timestamp (usually 4:01 PM ET)
    indicators JSON,  -- Day's final indicator values (MACD, RSI, Bollinger, etc.)
    summary_text TEXT NOT NULL,   -- Comprehensive daily analysis generated by LLM
    signals JSON,  -- Overall daily signals: {momentum, volatility, volume_trend}
    thought_trace TEXT,  -- Agent's reasoning and decision-making process
    model_used VARCHAR,  -- LLM model identifier (e.g., 'gpt-4')
    token_count INTEGER,  -- Number of tokens consumed
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (symbol, date_only)  -- One EOD summary per symbol per day
);

-- Index for fast lookups by symbol and date
CREATE INDEX IF NOT EXISTS idx_analyst_eod_symbol_date
    ON analyst_summaries(symbol, DATE(timestamp) DESC);

-- Index for recent summaries
CREATE INDEX IF NOT EXISTS idx_analyst_eod_recent
    ON analyst_summaries(created_at DESC);
