"""Pydantic models for the semi-auto multi-agent system."""

from src.server.models.endpoints import (
    ActionableSignalsResponse,
    AdminStatsResponse,
    AgentStateResponse,
    AnalystSymbolsResponse,
    BacktestPerformanceResponse,
    BacktestRunResponse,
    BacktestRunsResponse,
    BacktestTradesResponse,
    BalanceSheetResponse,
    BarsResponse,
    CashFlowResponse,
    CleanupResponse,
    CompanyOverviewResponse,
    ConversationResponse,
    DetailedHealthResponse,
    DividendsResponse,
    EarningsResponse,
    EODSummariesResponse,
    FlushCacheResponse,
    FundamentalsListResponse,
    HealthResponse,
    IncomeStatementResponse,
    IndicatorsResponse,
    IngestionStatusResponse,
    IntradayStatsResponse,
    LatestBarResponse,
    LatestEODResponse,
    LatestSignalResponse,
    PortfolioHealthResponse,
    PortfolioHistoryResponse,
    RecentEODsResponse,
    RecentSignalsResponse,
    RegistryResponse,
    RejectResponse,
    RootResponse,
    StrategyPerformanceResponse,
    TradesResponse,
    TriggerETLResponse,
    WatchlistMemberResponse,
    WatchlistResponse,
)
from src.server.models.task import (
    AgentOutput,
    AgentPlan,
    AgentReasoning,
    FunctionCall,
    FunctionCallEdit,
    PMFeedback,
    TaskItem,
    TaskList,
)
from src.server.models.responses import (
    ApprovalRequest,
    ContentSection,
    ExecutionResult,
    MetricRow,
    SemiAutoQueryRequest,
    SemiAutoResponse,
    SynthesisResult,
    TaskPreviewResponse,
)
from src.server.models.agent_decisions import OrderSignal, PMDecision
from src.server.models.query_intent import QueryIntent
from src.server.models.strategies import (
    BacktestInput,
    BacktestMetrics,
    BacktestOutput,
    BaseSignalOutput,
    Breakout52WInput,
    CandleInput,
    QuantIndicatorInput,
    CandleOutput,
    DataAvailabilityInput,
    DataAvailabilityOutput,
    EarningsDriftInput,
    FetchHistoricalDataOutput,
    GoldenCrossInput,
    HealthCheckOutput,
    HealthRiskParams,
    HealthViolation,
    HistoricalDataInput,
    MACDOutput,
    MeanReversionDailyInput,
    MeanReversionInput,
    MeanReversionLevels,
    MeanReversionMovingAverages,
    MeanReversionOutput,
    MeanReversionRecommendation,
    MeanReversionSignals,
    MeanReversionStatistics,
    MomentumBurstInput,
    MomentumInput,
    MomentumOutput,
    OpeningRangeBreakoutInput,
    PortfolioStatusOutput,
    PositionsSummaryOutput,
    RSIDivergenceInput,
    SimulationOutput,
    SnapshotSaveOutput,
    SnapshotWorthOutput,
    StrategyBaseInput,
    StrategySignalOutput,
    SwapPositionsOutput,
    VWAPReversionInput,
    VolatilityInput,
    VolatilityOutput,
    VolumeInput,
    VolumeOutput,
)

__all__ = [
    # task models
    "TaskItem",
    "TaskList",
    "AgentOutput",
    "AgentReasoning",
    "FunctionCall",
    "AgentPlan",
    "FunctionCallEdit",
    "PMFeedback",
    # response models
    "ExecutionResult",
    "TaskPreviewResponse",
    "ApprovalRequest",
    "SemiAutoResponse",
    "SemiAutoQueryRequest",
    # synthesis models
    "MetricRow",
    "ContentSection",
    "SynthesisResult",
    # skill input models
    "StrategyBaseInput",
    "QuantIndicatorInput",
    "MomentumInput",
    "VolatilityInput",
    "VolumeInput",
    "CandleInput",
    "MeanReversionInput",
    "BacktestInput",
    "DataAvailabilityInput",
    "HistoricalDataInput",
    "VWAPReversionInput",
    "OpeningRangeBreakoutInput",
    "RSIDivergenceInput",
    "MomentumBurstInput",
    "GoldenCrossInput",
    "Breakout52WInput",
    "MeanReversionDailyInput",
    "EarningsDriftInput",
    # skill output models
    "BaseSignalOutput",
    "MACDOutput",
    "MomentumOutput",
    "VolatilityOutput",
    "VolumeOutput",
    "CandleOutput",
    "BacktestMetrics",
    "BacktestOutput",
    "MeanReversionOutput",
    "MeanReversionStatistics",
    "MeanReversionMovingAverages",
    "MeanReversionSignals",
    "MeanReversionLevels",
    "MeanReversionRecommendation",
    "StrategySignalOutput",
    "PortfolioStatusOutput",
    "PositionsSummaryOutput",
    "HealthViolation",
    "HealthRiskParams",
    "HealthCheckOutput",
    "FetchHistoricalDataOutput",
    "DataAvailabilityOutput",
    "SnapshotSaveOutput",
    "SimulationOutput",
    "SnapshotWorthOutput",
    "SwapPositionsOutput",
    # endpoint models — health
    "HealthResponse",
    "DetailedHealthResponse",
    # endpoint models — portfolio
    "PortfolioHealthResponse",
    "PortfolioHistoryResponse",
    # endpoint models — admin
    "CleanupResponse",
    "AdminStatsResponse",
    # endpoint models — ingestion
    "IngestionStatusResponse",
    "TriggerETLResponse",
    "FlushCacheResponse",
    # endpoint models — agent
    "RejectResponse",
    "ConversationResponse",
    "AgentStateResponse",
    "RegistryResponse",
    # endpoint models — market
    "WatchlistResponse",
    "WatchlistMemberResponse",
    "BarsResponse",
    "LatestBarResponse",
    "TradesResponse",
    "IndicatorsResponse",
    "IntradayStatsResponse",
    # endpoint models — fundamentals
    "FundamentalsListResponse",
    "CompanyOverviewResponse",
    "DividendsResponse",
    "EarningsResponse",
    "IncomeStatementResponse",
    "BalanceSheetResponse",
    "CashFlowResponse",
    # endpoint models — analyst
    "AnalystSymbolsResponse",
    "EODSummariesResponse",
    "LatestEODResponse",
    "RecentEODsResponse",
    # endpoint models — strategy
    "ActionableSignalsResponse",
    "StrategyPerformanceResponse",
    "LatestSignalResponse",
    "RecentSignalsResponse",
    # endpoint models — backtest
    "BacktestRunsResponse",
    "BacktestRunResponse",
    "BacktestTradesResponse",
    "BacktestPerformanceResponse",
    # endpoint models — root
    "RootResponse",
    # classifier / decision models
    "QueryIntent",
    "OrderSignal",
    "PMDecision",
]
