"""strategies sub-package — re-exports all public input/output model names.

Import from this package exactly as you would from the old flat strategies.py:

    from src.server.models.strategies import BacktestInput, MomentumOutput
"""

from src.server.models.strategies.shared import (
    BaseSignalOutput,
    StrategyBaseInput,
    _FUZZY_MAP,
    _TIMEFRAME_ALIASES,
    _VALID_STRATEGIES,
    _normalise_timeframe,
)
from src.server.models.strategies.inputs import (
    BacktestInput,
    Breakout52WInput,
    CandleInput,
    DataAvailabilityInput,
    EarningsDriftInput,
    GoldenCrossInput,
    HistoricalDataInput,
    MeanReversionDailyInput,
    MeanReversionInput,
    MomentumBurstInput,
    MomentumInput,
    OpeningRangeBreakoutInput,
    QuantIndicatorInput,
    RSIDivergenceInput,
    VWAPReversionInput,
    VolatilityInput,
    VolumeInput,
)
from src.server.models.strategies.outputs import (
    BacktestMetrics,
    BacktestOutput,
    CandleOutput,
    DataAvailabilityOutput,
    FetchHistoricalDataOutput,
    HealthCheckOutput,
    HealthRiskParams,
    HealthViolation,
    MACDOutput,
    MeanReversionLevels,
    MeanReversionMovingAverages,
    MeanReversionOutput,
    MeanReversionRecommendation,
    MeanReversionSignals,
    MeanReversionStatistics,
    MomentumOutput,
    PortfolioStatusOutput,
    PositionsSummaryOutput,
    SimulationOutput,
    SnapshotSaveOutput,
    SnapshotWorthOutput,
    StrategySignalOutput,
    SwapPositionsOutput,
    VolatilityOutput,
    VolumeOutput,
)

__all__ = [
    # shared
    "StrategyBaseInput",
    "BaseSignalOutput",
    # inputs
    "QuantIndicatorInput",
    "MomentumInput",
    "VolatilityInput",
    "VolumeInput",
    "CandleInput",
    "MeanReversionInput",
    "BacktestInput",
    "DataAvailabilityInput",
    "HistoricalDataInput",
    "VWAPReversionInput",
    "OpeningRangeBreakoutInput",
    "RSIDivergenceInput",
    "MomentumBurstInput",
    "GoldenCrossInput",
    "Breakout52WInput",
    "MeanReversionDailyInput",
    "EarningsDriftInput",
    # outputs
    "MACDOutput",
    "MomentumOutput",
    "VolatilityOutput",
    "VolumeOutput",
    "CandleOutput",
    "BacktestMetrics",
    "BacktestOutput",
    "MeanReversionStatistics",
    "MeanReversionMovingAverages",
    "MeanReversionSignals",
    "MeanReversionLevels",
    "MeanReversionRecommendation",
    "MeanReversionOutput",
    "StrategySignalOutput",
    "PortfolioStatusOutput",
    "PositionsSummaryOutput",
    "HealthViolation",
    "HealthRiskParams",
    "HealthCheckOutput",
    "FetchHistoricalDataOutput",
    "DataAvailabilityOutput",
    "SnapshotSaveOutput",
    "SimulationOutput",
    "SnapshotWorthOutput",
    "SwapPositionsOutput",
]
