"""Daytona sandbox lifecycle management and DeepAgent integration.

Manages ephemeral Daytona sandboxes for quant strategy development.
Each sandbox contains a copy of the repo, runs OpenVSCode Server on port 3000,
and has a DeepAgent connected to it for AI-assisted code editing.

Sandbox creation is async (background task) to avoid blocking the FastAPI event loop.
Poll /v1/sandbox/{id}/status until status == "ready".
"""

from __future__ import annotations

import asyncio
import os
import random
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, AsyncGenerator

from daytona import (
    CreateSandboxFromImageParams,
    Daytona,
    DaytonaConfig,
    FileUpload,
    Image,
)
from deepagents import create_deep_agent
from langchain_daytona import DaytonaSandbox
from langchain_openai import ChatOpenAI

from src.common.utils import get_logger

logger = get_logger(__name__)

# ── Project root ──────────────────────────────────────────────────────────────

_PROJECT_ROOT = Path(__file__).parent.parent.parent.parent

# ── Sandbox name vocabulary ───────────────────────────────────────────────────

_ADJECTIVES = [
    "async", "eager", "silent", "rapid", "bold", "swift", "quiet",
    "bright", "calm", "fuzzy", "lucky", "golden", "cosmic", "lunar",
    "nimble", "steady", "vivid", "hollow", "amber", "silver",
]
_NOUNS = [
    "thimble", "anchor", "beacon", "cipher", "dagger", "ember",
    "fable", "glider", "harbor", "inkpot", "keystone", "lantern",
    "marmot", "nectar", "osprey", "parcel", "quiver", "ridgeline",
]

# ── Strategy scaffold template ────────────────────────────────────────────────

_STRATEGY_TEMPLATE = '''\
"""
New Strategy: {class_name}
Generated by Sandbox on {date}.
TODO: Replace this scaffold with your strategy logic.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Union

import pandas as pd

project_root = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(project_root))

from src.server.skills.quant.base_strategy import QuantStrategy
from src.server.skills.backtester.core.bt_types import StrategySignal, StrategyError


class {class_name}(QuantStrategy):
    """
    TODO: Describe what signal this strategy generates and when it fires.

    Entry conditions:
        - TODO

    Exit conditions:
        - TODO
    """

    def analyze_bars(
        self,
        df: pd.DataFrame,
        **params,
    ) -> Union[StrategySignal, StrategyError]:
        """Pure DataFrame analysis — no I/O.

        Args:
            df: OHLCV DataFrame with columns [open, high, low, close, volume].
                Sorted oldest-first. At least 30 rows recommended.
            **params: Strategy-specific parameters passed by the backtester.

        Returns:
            StrategySignal: Validated signal with action, confidence, price, reason.
            StrategyError:  Error response if analysis fails.
        """
        if df.empty or len(df) < 2:
            return StrategyError(error="Insufficient data", symbol=params.get("symbol", ""))

        # ── TODO: implement signal logic ──────────────────────────────────────
        # Example pattern:
        #   closes = df["close"]
        #   indicator = closes.rolling(20).mean()
        #   current = float(indicator.iloc[-1])
        #   signal_action = "buy" if <condition> else "sell" if <condition> else "hold"
        #   confidence = <float between 0.0 and 1.0>
        # ─────────────────────────────────────────────────────────────────────

        current_price = float(df["close"].iloc[-1])

        return StrategySignal(
            action="hold",
            confidence=0.0,
            current_price=current_price,
            reason="Scaffold — implement analyze_bars() logic.",
        )


if __name__ == "__main__":
    """Quick functional test — run this file directly to validate."""
    import sys
    sys.stdout.reconfigure(encoding="utf-8")

    print("=" * 60)
    print(f"Strategy Test: {class_name}")
    print("=" * 60)

    strategy = {class_name}()

    # Minimal synthetic DataFrame
    test_df = pd.DataFrame({{
        "open":   [100.0, 101.0, 102.0, 103.0, 104.0],
        "high":   [101.0, 102.0, 103.0, 104.0, 105.0],
        "low":    [99.0,  100.0, 101.0, 102.0, 103.0],
        "close":  [100.5, 101.5, 102.5, 103.5, 104.5],
        "volume": [1000,  1100,  1200,  1300,  1400],
    }})

    result = strategy.analyze_bars(test_df)
    print(f"Signal: {{result}}")
    print("\\n✅ Scaffold test passed — implement your logic above.")
    print("=" * 60)
'''

# ── Quant agent system prompt ─────────────────────────────────────────────────

_QUANT_SYSTEM_PROMPT = """\
You are a quantitative strategy development assistant with full access to a Python sandbox
containing the agentic-trader repository.

The quant strategies are in src/server/skills/quant/. Each strategy extends QuantStrategy
(from base_strategy.py) and must implement analyze_bars(df, **params) returning a
StrategySignal or StrategyError (from src/server/skills/backtester/core/bt_types.py).

You can: read/write files, run Python code with `python3`, execute pytest, install packages.

When creating or editing a strategy:
1. First read an existing strategy (e.g., golden_cross.py) to understand the pattern.
2. Edit the scaffold file already open in the editor, or create a new file following the
   same class structure.
3. Run the file directly: `python3 src/server/skills/quant/<strategy_file>.py`
4. Write a pytest test in tests/ following existing test patterns.
5. Run `python3 -m pytest tests/ -x -q` to validate.
6. Explain what signals the strategy generates and when it fires.

Available packages: pandas, numpy, pandas-ta, and everything in requirements.txt.
Always prefer testable, modular code. Do not write to data/ or logs/.
"""

# ── Max concurrent sandboxes guard ───────────────────────────────────────────

_MAX_SANDBOXES = 3

# ── In-memory sandbox registry ───────────────────────────────────────────────


@dataclass
class SandboxRecord:
    """Represents one active sandbox session."""
    sandbox_id: str
    name: str
    status: str                       # "creating" | "ready" | "error"
    created_at: datetime
    work_dir: str                     # /home/daytona/{name}
    daytona_sandbox: Any = field(default=None, repr=False)
    daytona_sandbox_id: str = ""      # Daytona-assigned sandbox ID (for TypeScript SDK)
    agent: Any = field(default=None, repr=False)
    vscode_url: str = ""
    terminal_url: str = ""            # Daytona web terminal (port 22222)
    error_msg: str | None = None


_sandboxes: dict[str, SandboxRecord] = {}
_sandboxes_lock = asyncio.Lock()  # guards limit check + insertion in start_creating


# ── Helpers ───────────────────────────────────────────────────────────────────


def _generate_name() -> str:
    """Return a random adjective-adjective-noun name (e.g. 'async-eager-thimble')."""
    return (
        f"{random.choice(_ADJECTIVES)}-"
        f"{random.choice(_ADJECTIVES)}-"
        f"{random.choice(_NOUNS)}"
    )


def _name_to_class(name: str) -> str:
    """Convert 'async-eager-thimble' → 'AsyncEagerThimble'."""
    return "".join(part.capitalize() for part in name.split("-"))


def _collect_upload_files(work_dir: str) -> list[FileUpload]:
    """Collect project files for upload, returning list of FileUpload objects.

    Uploads: src/server/skills/, src/common/, requirements.txt, config/
    Skips:   secret.json, prompts/, data/, logs/, __pycache__/, *.pyc, *.db, tests/, ui/
    """
    skip_dirs = {"__pycache__", ".git", "data", "logs", "tests", "ui", ".pytest_cache"}
    skip_exts = {".pyc", ".db", ".duckdb", ".log", ".sqlite", ".sqlite3"}
    skip_files = {"secret.json"}

    include_roots = [
        _PROJECT_ROOT / "src" / "server" / "skills",
        _PROJECT_ROOT / "src" / "common",
        _PROJECT_ROOT / "config",
    ]
    # Add requirements.txt as a single file
    req_file = _PROJECT_ROOT / "requirements.txt"

    uploads: list[FileUpload] = []
    seen: set[Path] = set()

    if req_file.exists() and req_file not in seen:
        seen.add(req_file)
        uploads.append(FileUpload(
            source=req_file.read_bytes(),
            destination=f"{work_dir}/requirements.txt",
        ))

    for root in include_roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path in seen or not path.is_file():
                continue
            if any(part in skip_dirs for part in path.parts):
                continue
            if path.suffix in skip_exts:
                continue
            if path.name in skip_files:
                continue
            seen.add(path)
            rel = path.relative_to(_PROJECT_ROOT)
            uploads.append(FileUpload(
                source=path.read_bytes(),
                destination=f"{work_dir}/{rel.as_posix()}",
            ))

    logger.info(f"[sandbox] collected {len(uploads)} files for upload")
    return uploads


def _build_strategy_scaffold(name: str, work_dir: str) -> FileUpload:
    """Build the strategy template file as a FileUpload."""
    class_name = _name_to_class(name)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    content = _STRATEGY_TEMPLATE.format(class_name=class_name, date=date_str)
    safe_name = name.replace("-", "_")
    destination = f"{work_dir}/src/server/skills/quant/new_strategy_{safe_name}.py"
    return FileUpload(source=content.encode(), destination=destination)


def _upload_in_batches(sandbox: Any, uploads: list[FileUpload], batch_size: int = 50) -> None:
    """Upload files in batches to avoid SDK size limits."""
    for i in range(0, len(uploads), batch_size):
        batch = uploads[i: i + batch_size]
        sandbox.fs.upload_files(batch)
        logger.debug(f"[sandbox] uploaded batch {i // batch_size + 1} ({len(batch)} files)")


# ── Core creation logic (runs in thread via asyncio.to_thread) ────────────────


def _create_sandbox_sync(record: SandboxRecord, api_key: str, openai_key: str) -> None:
    """Synchronous sandbox creation — called from asyncio.to_thread to avoid blocking."""
    try:
        image = (
            Image.debian_slim("3.12")
                 .run_commands(
                     "apt-get update -qq && "
                     "apt-get install -y --no-install-recommends git curl ca-certificates"
                 )
                 .run_commands(
                     "curl -fsSL https://code-server.dev/install.sh "
                     "| sh -s -- --method=standalone --prefix=/usr/local"
                 )
                 .pip_install([
                     "pandas",
                     "numpy",
                     "pandas-ta",
                     "requests",
                     "pytz",
                     "python-json-logger",
                     "pytest",
                     "pytest-asyncio",
                 ])
        )

        client = Daytona(DaytonaConfig(api_key=api_key))
        logger.info(f"[sandbox:{record.name}] creating Daytona sandbox...")

        sandbox = client.create(
            CreateSandboxFromImageParams(
                image=image,
                ephemeral=True,
                auto_stop_interval=0,
                auto_delete_interval=0,
            ),
            timeout=0,  # no SDK-level timeout; we manage it ourselves
            on_snapshot_create_logs=lambda msg: logger.debug(f"[sandbox:{record.name}] build: {msg}"),
        )
        logger.info(f"[sandbox:{record.name}] sandbox created: {sandbox.id}")

        # ── Upload project files ──
        logger.info(f"[sandbox:{record.name}] uploading project files...")
        uploads = _collect_upload_files(record.work_dir)
        _upload_in_batches(sandbox, uploads)
        logger.info(f"[sandbox:{record.name}] upload complete")

        # ── Upload strategy scaffold ──
        scaffold = _build_strategy_scaffold(record.name, record.work_dir)
        quant_dir = f"{record.work_dir}/src/server/skills/quant"
        sandbox.process.exec(f"mkdir -p {quant_dir}", timeout=10)
        sandbox.fs.upload_files([scaffold])
        logger.info(f"[sandbox:{record.name}] strategy scaffold uploaded: {scaffold.destination}")

        # ── Git init for change tracking ──
        git_result = sandbox.process.exec(
            f"cd {record.work_dir} && "
            f"git config user.email 'sandbox@local' && "
            f"git config user.name 'Sandbox' && "
            f"git init && git add -A && git commit -m 'initial' --allow-empty",
            timeout=60,
        )
        logger.info(f"[sandbox:{record.name}] git init: {(git_result.result or '').strip()[-120:]}")

        # ── Start code-server ──
        sandbox.process.exec(
            f"nohup code-server "
            f"--bind-addr 0.0.0.0:3000 "
            f"--auth none "
            f"--disable-telemetry "
            f"{record.work_dir} "
            f"> /tmp/code-server.log 2>&1 &",
            timeout=15,
        )
        logger.info(f"[sandbox:{record.name}] code-server started on port 3000")

        # ── Get preview URLs ──
        preview = sandbox.get_preview_link(3000)
        vscode_url = preview.url if hasattr(preview, "url") else str(preview)
        logger.info(f"[sandbox:{record.name}] VS Code URL: {vscode_url}")

        term_preview = sandbox.get_preview_link(22222)
        terminal_url = term_preview.url if hasattr(term_preview, "url") else str(term_preview)
        logger.info(f"[sandbox:{record.name}] terminal URL: {terminal_url}")

        # ── Build DeepAgent ──
        safe_name = record.name.replace("-", "_")
        scaffold_rel = f"src/server/skills/quant/new_strategy_{safe_name}.py"
        scaffold_prompt = (
            f"\n\nYour PRIMARY task for this session is the scaffold strategy file at:\n"
            f"  {scaffold_rel}\n"
            f"Read this file first. When the user asks you to implement the strategy, "
            f"edit this file in place using your file tools."
        )
        backend = DaytonaSandbox(sandbox=sandbox)
        agent = create_deep_agent(
            model=ChatOpenAI(model="gpt-4o", api_key=openai_key),
            system_prompt=_QUANT_SYSTEM_PROMPT + scaffold_prompt,
            backend=backend,
        )
        logger.info(f"[sandbox:{record.name}] DeepAgent ready")

        # ── Commit to record ──
        record.daytona_sandbox = sandbox
        record.daytona_sandbox_id = sandbox.id
        record.agent = agent
        record.vscode_url = vscode_url
        record.terminal_url = terminal_url
        record.status = "ready"
        logger.info(f"[sandbox:{record.name}] ✅ sandbox ready")

    except Exception as exc:
        record.status = "error"
        record.error_msg = str(exc)
        logger.error(f"[sandbox:{record.name}] ❌ creation failed: {exc}", exc_info=True)


# ── Public API ────────────────────────────────────────────────────────────────


async def start_creating(api_key: str, openai_key: str) -> str:
    """Register a new sandbox and kick off async creation.

    Returns the sandbox_id immediately. Creation continues in background.
    Callers should poll get_status() until status == "ready".

    Args:
        api_key:    Daytona API key.
        openai_key: OpenAI API key for the DeepAgent model.

    Returns:
        sandbox_id (str): UUID for the new sandbox session.

    Raises:
        RuntimeError: If _MAX_SANDBOXES concurrent sessions are already active.
    """
    async with _sandboxes_lock:
        active = [r for r in _sandboxes.values() if r.status in ("creating", "ready")]
        if len(active) >= _MAX_SANDBOXES:
            raise RuntimeError(
                f"Max concurrent sandboxes ({_MAX_SANDBOXES}) reached. "
                "Publish or destroy an existing sandbox first."
            )

        sandbox_id = str(uuid.uuid4())
        name = _generate_name()
        work_dir = f"/home/daytona/{name}"
        record = SandboxRecord(
            sandbox_id=sandbox_id,
            name=name,
            status="creating",
            created_at=datetime.now(timezone.utc),
            work_dir=work_dir,
        )
        _sandboxes[sandbox_id] = record

    asyncio.create_task(
        asyncio.to_thread(_create_sandbox_sync, record, api_key, openai_key),
        name=f"sandbox-create-{name}",
    )
    logger.info(f"[sandbox] creation task queued: {name} ({sandbox_id})")
    return sandbox_id


def get_status(sandbox_id: str) -> SandboxRecord | None:
    """Return the SandboxRecord for the given ID, or None if not found."""
    return _sandboxes.get(sandbox_id)


async def stream_agent(sandbox_id: str, query: str) -> AsyncGenerator[str, None]:
    """Stream agent tokens for a query against the sandbox's DeepAgent.

    Args:
        sandbox_id: ID of a sandbox in "ready" status.
        query:      User's natural language request.

    Yields:
        str tokens as the model streams its response.

    Raises:
        KeyError:   If sandbox_id is not found.
        RuntimeError: If sandbox is not in "ready" status.
    """
    record = _sandboxes.get(sandbox_id)
    if record is None:
        raise KeyError(f"Sandbox not found: {sandbox_id}")
    if record.status != "ready":
        raise RuntimeError(f"Sandbox not ready (status={record.status})")

    async for event in record.agent.astream_events(
        {"messages": [{"role": "user", "content": query}]},
        version="v2",
    ):
        if event["event"] == "on_chat_model_stream":
            chunk = event["data"].get("chunk")
            token = getattr(chunk, "content", "") or ""
            if token:
                yield token


async def publish_sandbox(sandbox_id: str, mode: str = "all") -> list[str]:
    """Download changed files from sandbox to local repo, then destroy it.

    Args:
        sandbox_id: ID of a sandbox in "ready" status.
        mode: "all"  — modified tracked files + new untracked files (default).
              "new"  — only untracked new files (git ls-files --others).

    Returns:
        List of relative file paths that were published to the local repo.

    Raises:
        KeyError:     If sandbox_id is not found.
        RuntimeError: If sandbox is not in "ready" status.
    """
    record = _sandboxes.get(sandbox_id)
    if record is None:
        raise KeyError(f"Sandbox not found: {sandbox_id}")
    if record.status != "ready":
        raise RuntimeError(f"Sandbox not ready (status={record.status})")

    def _sync_publish() -> list[str]:
        sandbox = record.daytona_sandbox
        wdir = record.work_dir

        if mode == "new":
            # Only untracked new files
            raw = sandbox.process.exec(
                f"cd {wdir} && git ls-files --others --exclude-standard",
                timeout=30,
            ).result or ""
        else:
            # Modified tracked files + untracked new files (single round-trip)
            raw = sandbox.process.exec(
                f"cd {wdir} && git diff --name-only HEAD; git ls-files --others --exclude-standard",
                timeout=30,
            ).result or ""

        changed = list(dict.fromkeys(          # preserve order, deduplicate
            line.strip() for line in raw.splitlines() if line.strip()
        ))
        logger.info(f"[sandbox:{record.name}] publish mode={mode} — {len(changed)} file(s): {changed}")

        published: list[str] = []
        for rel_path in changed:
            try:
                content = sandbox.fs.download_file(f"{record.work_dir}/{rel_path}")
                if content is None:
                    logger.warning(f"[sandbox:{record.name}] download returned None for {rel_path}")
                    continue
                local = _PROJECT_ROOT / rel_path
                local.parent.mkdir(parents=True, exist_ok=True)
                local.write_bytes(content)
                published.append(rel_path)
                logger.info(f"[sandbox:{record.name}] published: {rel_path}")
            except Exception as exc:
                logger.error(f"[sandbox:{record.name}] failed to publish {rel_path}: {exc}")

        # Destroy sandbox (ephemeral → auto-deleted on stop)
        try:
            sandbox.stop()
            logger.info(f"[sandbox:{record.name}] sandbox stopped and queued for deletion")
        except Exception as exc:
            logger.warning(f"[sandbox:{record.name}] stop failed (may already be stopped): {exc}")

        return published

    published = await asyncio.to_thread(_sync_publish)
    del _sandboxes[sandbox_id]
    return published


async def delete_sandbox(sandbox_id: str) -> None:
    """Force-stop and remove a sandbox without publishing changes.

    Args:
        sandbox_id: ID of any sandbox (any status).

    Raises:
        KeyError: If sandbox_id is not found.
    """
    record = _sandboxes.get(sandbox_id)
    if record is None:
        raise KeyError(f"Sandbox not found: {sandbox_id}")

    def _sync_delete() -> None:
        if record.daytona_sandbox is not None:
            try:
                record.daytona_sandbox.stop()
            except Exception as exc:
                logger.warning(f"[sandbox:{record.name}] delete/stop failed: {exc}")

    await asyncio.to_thread(_sync_delete)
    del _sandboxes[sandbox_id]
    logger.info(f"[sandbox:{record.name}] deleted (no publish)")


async def cleanup_all() -> None:
    """Stop all active sandboxes — called during server shutdown."""
    ids = list(_sandboxes.keys())
    results = await asyncio.gather(
        *[delete_sandbox(sid) for sid in ids],
        return_exceptions=True,
    )
    for sid, result in zip(ids, results):
        if isinstance(result, Exception):
            logger.warning(f"[sandbox] cleanup failed for {sid}: {result}")
    logger.info(f"[sandbox] cleanup complete ({len(ids)} sandbox(es) stopped)")


if __name__ == "__main__":
    """Smoke test: verify imports and name generation."""
    import sys
    sys.stdout.reconfigure(encoding="utf-8")

    print("=" * 60)
    print("sandbox_service.py — import & name-gen smoke test")
    print("=" * 60)

    for _ in range(5):
        name = _generate_name()
        cls = _name_to_class(name)
        print(f"  {name!r:40s} → {cls!r}")

    print()
    print("  Template preview (first 10 lines):")
    preview = _STRATEGY_TEMPLATE.format(class_name="TestStrategy", date="2026-04-08")
    for line in preview.splitlines()[:10]:
        print(f"    {line}")

    print()
    print("✅ Smoke test passed — no import errors.")
    print("=" * 60)
